"""Helpers for installer-managed systemd files.

The shell installer still owns service enable/restart behavior. This module
keeps file rendering testable: seed preserved /etc/default files and render
unit templates with explicit placeholder values.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from .util import fail, info


_TOKEN_RE = re.compile(r"__([A-Z][A-Z0-9_]*)__")
_KEY_RE = re.compile(r"[A-Z][A-Z0-9_]*")


def parse_replacement(raw: str) -> tuple[str, str]:
    """Parse a CLI ``KEY=VALUE`` replacement."""
    if "=" not in raw:
        fail(f"systemd template replacement must be KEY=VALUE, got: {raw!r}")
    key, value = raw.split("=", 1)
    if not _KEY_RE.fullmatch(key):
        fail(f"invalid systemd template replacement key: {key!r}")
    return key, value


def default_env_body(service_name: str) -> str:
    return (
        f"# Generated by setup-hermes.sh \u2014 extra env for {service_name}.service.\n"
        "# Edits here survive re-runs of the installer. Keep QUAY_ADMIN_TOKEN in\n"
        "# <HERMES_HOME>/auth/quay.env; setup-hermes.sh generates and preserves it.\n"
    )


def seed_default_env(out: Path, service_name: str, *, chown_root: bool = True) -> bool:
    """Create an operator override env file if it does not already exist.

    Returns True when a file was written and False when an existing file was
    preserved.
    """
    if out.exists():
        if not out.is_file():
            fail(f"default env path exists but is not a file: {out}")
        info(f"{out} already present (preserving)")
        return False

    _ensure_dir(out.parent, mode=0o755, chown_root=chown_root)
    info(f"seeding {out}")
    _write_text_file(
        out,
        default_env_body(service_name),
        mode=0o644,
        chown_root=chown_root,
    )
    return True


def render_unit_template(template: Path, replacements: dict[str, str]) -> str:
    try:
        text = template.read_text(encoding="utf-8")
    except FileNotFoundError:
        fail(f"systemd unit template not found: {template}")

    for key, value in replacements.items():
        text = text.replace(f"__{key}__", value)

    unresolved = sorted({f"__{key}__" for key in _TOKEN_RE.findall(text)})
    if unresolved:
        fail(
            "unresolved systemd template token(s) in "
            f"{template}: {', '.join(unresolved)}"
        )
    return text


def render_systemd_unit(
    template: Path,
    out: Path,
    replacements: dict[str, str],
    *,
    chown_root: bool = True,
) -> None:
    rendered = render_unit_template(template, replacements)
    _write_text_file(out, rendered, mode=0o644, chown_root=chown_root)


def _write_text_file(path: Path, body: str, *, mode: int, chown_root: bool) -> None:
    _ensure_dir(path.parent, chown_root=False)
    path.write_text(body, encoding="utf-8")
    path.chmod(mode)
    if chown_root and hasattr(os, "chown"):
        os.chown(path, 0, 0)


def _ensure_dir(path: Path, *, mode: int | None = None, chown_root: bool) -> None:
    path.mkdir(parents=True, exist_ok=True)
    if mode is not None:
        path.chmod(mode)
    if chown_root and hasattr(os, "chown"):
        os.chown(path, 0, 0)
